version: "3"
services:
  opensearch:
    image: opensearchproject/opensearch:2.5.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"  # OpenSearch HTTP API
    volumes:
      - opensearch-data:/usr/share/opensearch/data  # Persist OpenSearch data

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200  # Connect to the OpenSearch service
    ports:
      - "5601:5601"  # OpenSearch Dashboards UI

volumes:
  opensearch-data:
    driver: local  # Use local storage for data persistence
